### ISSUE TITLE
vim-cmake doesn't populate all the errors in the quickfix

### ISSUE THREAD

**Issue by GGCristo** [cdelledonne/vim-cmake#11]
**Describe the bug**
Quickfix doesn't populate all the errors

**To Reproduce**
:CMakeBuild
[Open quickfix]
**Expected behavior**
All the errors and warnings must be present in the quickfix.

**Screenshots**
![Screenshot_20200913_212624](https://user-images.githubusercontent.com/58046649/93027931-466de580-f608-11ea-868d-4f0dc698e33c.png)
If I fix the second bug...
![Screenshot_20200913_213100](https://user-images.githubusercontent.com/58046649/93027948-72896680-f608-11ea-99e4-84a119248a14.png)

**Other info**
- OS: Linux (ArchLinux)
- Vim/Neovim version: 8.2.1634
- Vim-CMake version (5th line in `:help cmake`): 0.3.0

**Additional context**
:chistory tell me I am in a CMakeBuild quickfix.
The errors are detected by other plugins.
I will update the issue if I figure out anything else.

**Comment by cdelledonne** [comment]
Hey, thanks for reporting.

I've been a little busy. Let me look into it this weekend.

**Comment by cdelledonne** [comment]
Actually that was hopefully an easy fix (#12). I hadn't tested the feature in Vim enough (I use Neovim).

Could you checkout the branch `fix-output-parsing-vim` and see if that fixes your issue? Thanks!

**Comment by GGCristo** [comment]
So far so good, but I've only tested it in two projects and the minimal one of the images.
Thanks and sorry if I am too persistent.

**Comment by cdelledonne** [comment]
I actually appreciate bug reports and feature requests, it's what make open-source software better :) I'll merge the patch and close the issue, feel free to re-open if the problem occurs again.

**Comment by jowu598** [comment]
I reproduced this in latest version.
