### ISSUE TITLE
Additional project generation options

### ISSUE THREAD

**Issue by ivan-volnov** [cdelledonne/vim-cmake#13]
Thank you very much for a such great plugin.

In order to use it personally I need some more project generation options:

```
let g:cmake_export_compile_commands = 1
let g:cmake_project_generator = 'ninja'
let g:cmake_cxx_compiler = 'path to executable'
let g:cmake_c_compiler = 'path to executable'
let g:cmake_toolchain_file = 'path to executable'
```

Or just an array of custom generation options:

```
let g:cmake_generate_options = []
```

I suppose they must be useful for another people.

**Comment by cdelledonne** [comment]
Hi, thank you for your kind feedback!

Indeed having an option for default `:CMakeGenerate` options would be nice. I would be in favour of `g:cmake_generate_options`, for consistency with `g:cmake_build_options`.

Would you be interested in submitting a pull request for this?

**Comment by ivan-volnov** [comment]
Ok, let it be g:cmake_generate_options.

> Would you be interested in submitting a pull request for this?

You know, I've tried. But it turned out that it's quite hard for me now to get into the coding process at this project.
So, feel free to implement it. And I'm looking forward to updating =) Thanks.

**Comment by cdelledonne** [comment]
I've added `g:cmake_generate_options`, please try if that works and let me know :)

**Comment by ivan-volnov** [comment]
It works! Thank you very much!

**Comment by Nullarity** [comment]
> It works! Thank you very much!

can you please explain to me how it works? When I try to use `let g:cmake_generate_options=["-D..."]` the plugin runs this: `cmake -DCMAKE_TOOLCHAIN_FILE=/home/nullarity/vcpkg/scripts/buildsystems/vcpkg.cmake -S . -B Debug` which is not correct.

**Comment by ivan-volnov** [comment]
@Nullarity
Well, I don't use this plugin anymore.
But here is my last config config:

```
let g:cmake_generate_options = ['-GNinja',
            \ '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON',
            \ '-DCMAKE_MAKE_PROGRAM:INTERNAL=samu',
            \ '-DCMAKE_CXX_COMPILER_LAUNCHER:INTERNAL=ccache',
            \ '-DCMAKE_CXX_COMPILER:STRING=clang++15',
            \ '-DCMAKE_C_COMPILER_LAUNCHER:INTERNAL=ccache',
            \ '-DCMAKE_C_COMPILER:STRING=clang15']
let g:cmake_default_config = 'Debug'
let g:cmake_build_options = ['-j16']
let g:cmake_root_markers = ['CMakeLists.txt.user']
let g:cmake_build_dir_location = '..'
let g:cmake_link_compile_commands = 1
let g:cmake_console_size = 10
```

You can figure it out using given example.
