### ISSUE TITLE
Wrong root directory for CMakeGenerate output

### ISSUE THREAD

**Issue by ivan-volnov** [cdelledonne/vim-cmake#15]
**Describe the bug**
CMakeGenerate ignores root folder found by g:cmake_root_markers

**To Reproduce**
1. Setup project structure like this:

```
/Users/user/project/
├── .git
├── CMakeLists.txt
└── src
    └── main.cpp
```

2. Add to config:

```
let g:cmake_generate_options = ['-GNinja', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON']
let g:cmake_root_markers = ['.git']
let g:cmake_link_compile_commands = 1
```

3. Open file project/src/main.cpp in vim
4. Execute :CMakeGenerate
5. As result project structure will be:

```
/Users/user/project/
├── .git
├── CMakeLists.txt
├── compile_commands.json -> Debug/compile_commands.json
└── src
    ├── Debug
    └── main.cpp
```

**Expected behavior**
Directory Debug must be created at the project root.
We also have a broken link here. compile_commands.json points to a not existing directory.
It also must be configurable to set path for the Debug folder. For example '..' (parent directory of the project root)

Also g:cmake_link_compile_commands option should imply -DCMAKE_EXPORT_COMPILE_COMMANDS=ON command line argument to cmake.

**Comment by cdelledonne** [comment]
Hi, thanks for reporting the issue. It seems indeed that there's a bug with setting the root directory when generating project files and when building. I'm not sure I have time to look into this soon, otherwise I'll do it in a week or so.

Regarding
> It also must be configurable to set path for the Debug folder. For example '..' (parent directory of the project root)
>
> Also g:cmake_link_compile_commands option should imply -DCMAKE_EXPORT_COMPILE_COMMANDS=ON command line argument to cmake.

Could you open separate feature requests, one for each suggestion?

Anyway, thanks a lot for your bug reports and feature requests, they are very appreciated.

**Comment by cdelledonne** [comment]
I finally managed to look into this issue.

I submitted #17. Could you checkout the branch `set-correct-source-and-build-dirs` and see if that fixes your issue? Thanks!

**Comment by ivan-volnov** [comment]
Thank you very much. It works!

I also opened separate feature requests for the suggestions.
