### ISSUE TITLE
g:cmake_link_compile_commands option should imply -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

### ISSUE THREAD

**Issue by ivan-volnov** [cdelledonne/vim-cmake#18]
g:cmake_link_compile_commands option should imply -DCMAKE_EXPORT_COMPILE_COMMANDS=ON command line argument to cmake.

**Comment by cdelledonne** [comment]
Implemented in 301e37bd022aaeffa7585dbe4df614c7a4bb7cd4
