### ISSUE TITLE
AirlineRefresh is called even if Airline plugin is not installed.

### ISSUE THREAD

**Issue by sridharsridha** [cdelledonne/vim-cmake#2]
**Describe the bug**
Error detected while processing function <SNR>181_NeovimStdoutCallback[3]..<SNR>185_CMakeConsoleCb:
line   13:
E492: Not an editor command: AirlineRefresh

**To Reproduce**
No special steps it, is hit by default.

**Expected behavior**
AirlineRefresh needs to be called only if it exist:

```
if exists(":AirlineRefresh")
    execute "AirlineRefresh"
endif
```

**Screenshots**

**Other info**
- OS:
- Vim/Neovim version:
- Vim-CMake version (5th line in `:help cmake`):

**Additional context**

**Comment by cdelledonne** [comment]
Hello, first issue reporter!

You're right, `AirlineRefresh` shouldn't be called when it is not defined. Will fix this soon. Thanks!

**Comment by cdelledonne** [comment]
I just pushed a fix, please update your plugin and let me know if that works

**Comment by sridharsridha** [comment]
Thank you for fixing this. Yes, I do not get the ` Not an editor command: AirlineRefresh` error.
