### ISSUE TITLE
Add command to call ctest in build dir

### ISSUE THREAD

**Issue by maxnoe** [cdelledonne/vim-cmake#23]
**Is your feature request related to a problem? Please describe.**

It would be cool to also be able to run `ctest -v` in the current build directory

**Describe the solution you'd like**

A new command `CTest` that runs ctest in the current build dir.

**Comment by cdelledonne** [comment]
Hi, thanks for posting this!

When calling `enable_testing()`, CMake adds a `test` target to the build system. That is, to run `ctest` in the current build directory, you can do
```
:CMakeBuild test
```
If you look at the Makefile generated after calling `:CMakeGenerate`, the target `test` look like
```make
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/path/to/ctest --force-new-ctest-process $(ARGS)
```
which means that to pass command-line arguments to `ctest`, e.g. `-V`, you have to do
```
:CMakeBuild test -- ARGS="-V"
```

For the above reason, I think it would make sense to indeed define a new command that invokes `ctest` and passes the command-line options to it directly. I would probably call it `:CMakeTest` to stay consistent with the rest of the commands defined by this plugin.

What do you think? Would you also be interested in submitting a PR for this?
