### ISSUE TITLE
don't create compile_commands.json soft link if cmake gives error

### ISSUE THREAD

**Issue by GopherJ** [cdelledonne/vim-cmake#29]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when an invalid compile_commands.json link has been created

**Describe the solution you'd like**

create the link after successfully running cmake command
**Describe alternatives you've considered**

**Additional context**

**Comment by cdelledonne** [comment]
Hi, thank you for posting this.

Your request makes sense. I have a question regarding this though: if a `compile_commands.json` already exists, then you run `:CMakeGenerate` and that returns an error, what would you like to happen? Nothing? Or should the old `compile_commands.json` be deleted?

By the way, would you be interested in preparing a pull request for this yourself?

**Comment by cdelledonne** [comment]
As of abf3d39666942fe68657cce303c534d865d06567, a link to the `compile_commands.json` file is only created on a successful `:CMakeGenerate` and on a successful `:CMakeSwitch`.
