### ISSUE TITLE
can not create compile_commands.json

### ISSUE THREAD

**Issue by matu3ba** [cdelledonne/vim-cmake#31]
**Describe the bug**
vim-cmake does generate the Makefile and cmake objects in folder Debug, but it does not generate a compile_commands.json necessary for clangd or any other c++ language server.

**To Reproduce**
1. Make sure you have folder called Debug.
2. Run :CMakeGenerate

**Expected behavior**
The compile_commands.json should be created. However it is not, which makes clangd unusable.

**Screenshots**
(would show that clangd does not find files)

**Other info**
- OS: Endeavour (rolling release Arch derivate)
- Vim/Neovim version: NVIM v0.5.0-dev+1133-g0869cbd55 (appimage)
- Vim-CMake version (5th line in `:help cmake`): 0.5.0

**Additional context**
[Here](https://stackoverflow.com/a/45781334) is a hint that the compile_commands.json needs a second invocation of cmake. Did you skip this at some point? Otherwise I would suggest creating another command to generate the compile_commands.json.

Probably they changed the behavior such that cmake does not invoke itself a second time?!

`set(CMAKE_EXPORT_COMPILE_COMMANDS ON)` works as expected, so maybe the cmake CLI interface got changed?!

**Comment by cdelledonne** [comment]
Hi, sorry for replying this late.

I cannot reproduce your issue at the moment. What is your Vim-CMake configuration? In particular, is `g:cmake_link_compile_commands` set?

I will anyway look into the problem more carefully as soon as I find some time.

**Comment by matu3ba** [comment]
@cdelledonne As of now I dont use the plugin anymore, since setting up debug options with cmake is a pain in the ass: https://github.com/mfussenegger/nvim-dap/wiki/Debug-symbols-in-various-languages-and-build-systems#cmake and I would prefer having always debug symbols for developing.

Personally I think having per-project settings for cmake works best, either with a [config](https://github.com/matu3ba/dotfiles/blob/de9ca808e347c71cb38f61259dd12111c4ceda97/.config/nvim/init.lua#L70), [scripting](https://github.com/matu3ba/telescope-project-scripts.nvim) or [harpoon](https://github.com/matu3ba/telescope-project-scripts.nvim) (not sure what is best usable in vim).

**Comment by matu3ba** [comment]
closed with worksforme and clangd appears now to look inside build folders for compile_command.json
