### ISSUE TITLE
:CMakeGenerate only adds -DCMAKE_BUILD_TYPE flag on first time

### ISSUE THREAD

**Issue by Andoku** [cdelledonne/vim-cmake#32]
### Bug description
If I use commands:
`:CMakeGenerate Debug` or `:CMakeGenerate! Debug` 
It adds `-DCMAKE_BUILD_TYPE=Debug` flag only if folder build/Debug doesn't exist.
If I run it the second time it doesn't add this flag

### To Reproduce
1. Run `:CMakeGenerate! Debug`
2. Run `:CMakeGenerate! Debug` second time

### Expected behavior
Expected to always add `-DCMAKE_BUILD_TYPE=Debug` or `-DCMAKE_BUILD_TYPE=Release` flags

### Screenshots
First time running `:CMakeGenerate! Debug`:
<img width="879" alt="Снимок экрана 2021-07-15 в 00 43 49" src="https://user-images.githubusercontent.com/669031/125697067-1cb08230-3413-4bff-b5fc-d23fc13d2537.png">

Second time running `:CMakeGenerate! Debug`:
<img width="859" alt="Снимок экрана 2021-07-15 в 00 44 45" src="https://user-images.githubusercontent.com/669031/125697140-9aed7ba7-9846-46b0-b248-90debe761b1d.png">

### Other info
- OS: MacOS Big Sur
- Vim/Neovim version: 8.2.2681 (171)
- Vim-CMake version (5th line in `:help cmake`): 0.6.1

**Comment by cdelledonne** [comment]
Hi, thanks a lot for reporting this!

Indeed the plugin behaves as you reported, which is wrong. What I think should happen is:
1. When the user calls `:CMakeGenerate Debug [...]` for the first time, the `cmake` command should be called with `-DCMAKE_BUILD_TYPE=Debug`
2. If the user calls `:CMakeGenerate Debug [...]` again, and the `Debug` folder already exists, there's no need to add the `-DCMAKE_BUILD_TYPE=Debug` argument, unless the user forces it explicitly with `:CMakeGenerate Debug -DCMAKE_BUILD_TYPE=Something`
3. If the user calls `:CMakeGenerate! Debug [...]`, and thus the `Debug` folder is gets wiped before generating the build system again, the `cmake` command should be called with `-DCMAKE_BUILD_TYPE=Debug`

Would you agree?

**Comment by Andoku** [comment]
Sounds reasonable

**Comment by cdelledonne** [comment]
Actually, I think it would be much easier (and probably more robust) to always pass the `-DCMAKE_BUILD_TYPE` option, as you had originally suggested.

Anyway, would you be interested in preparing a PR for this? It should not be too hard. Otherwise, I'll submit a fix soon.
