### ISSUE TITLE
Blank terminal after build or generate

### ISSUE THREAD

**Issue by zirco740** [cdelledonne/vim-cmake#39]
### Bug description
After running :CMakeGenerate or :CMakeBuild, a blank terminal is generated but it was doing nothing. I have made sure that the command leads to cmake executable is correct. The terminal remains blank no matter how long I waited for it.

### To Reproduce
1.  Run :CMakeGenerate or :CMakeBuild with default config

### Expected behavior
Successfully generate build files

### Behavior with minimal `.vimrc`
A clear and concise description of what happens whe trying to reproduce the bug with a minimal `.vimrc`. Ideally, a minimal `.vimrc` only contains configuration for this plugin, and nothing else. If the minimal `.vimrc` used is more complicated, please post the content here.
The only configuration of this plugin is Plug 'cdelledonne/vim-cmake'. 
This problem occurs without all other plugins too.

### Screenshots
![image](https://user-images.githubusercontent.com/54179931/151667087-7a6817c8-92df-4a9d-9fef-10218e85d93f.png)

### Other info
- OS: Windows 11
- Vim/Neovim version: Neovim 0.7
- Vim-CMake version (5th line in `:help cmake`): 0.6.2

**Comment by cdelledonne** [comment]
Hi, thank you for reporting this.

Which terminal emulator are you using on Windows? I'm not too familiar with the available options, but will try to investigate what might cause the issue. I suspect your terminal can't run `bash` scripts natively, but not sure (as an example, [Windows Terminal](https://en.wikipedia.org/wiki/Windows_Terminal) should).

**Comment by zirco740** [comment]
> Hi, thank you for reporting this.
> 
> Which terminal emulator are you using on Windows? I'm not too familiar with the available options, but will try to investigate what might cause the issue. I suspect your terminal can't run `bash` scripts natively, but not sure (as an example, [Windows Terminal](https://en.wikipedia.org/wiki/Windows_Terminal) should).
> 
> Support for Windows is still a little vague, I admit, as I'm less familiar with it. But we can try to improve there.

I was using Windows Terminal, and I have also tried to change the command a few times to see if the default command cannot call CMake, but seems like it has nothing to do with the default command.

**Comment by zirco740** [comment]
One thing that's very strange is when I hit the enter key in that terminal, a heart-shaped icon pops up.

**Comment by cdelledonne** [comment]
Lovely :heart:

Then it looks like we have no support for Windows at the moment :) I will try to set up a virtual machine with Windows and look into the problem. I will keep you posted, but I'm not sure when I'll have time for it (I hope in the next few days).

**Comment by cdelledonne** [comment]
While I get around to setting up a Windows machine, could you please try something? In `autoload/cmake/job.vim`, replace
https://github.com/cdelledonne/vim-cmake/blob/d82f2a185b17f8390877a8bc4d112dadabe3cea6/autoload/cmake/job.vim#L40
with
```vim
        let l:term = termopen([a:command], l:options)
```
Basically pass a list to `termopen()` instead of a string. From `:h jobstart()`
```
jobstart({cmd}[, {opts}])				*jobstart()*
		Spawns {cmd} as a job.
		If {cmd} is a List it runs directly (no 'shell').
		If {cmd} is a String it runs in the 'shell', like this:
		  :call jobstart(split(&shell) + split(&shellcmdflag) + ['{cmd}'])
		(See |shell-unquoting| for details.)
```
I'm curious to see what happens if we run the Bash command "directly".

**Comment by zirco740** [comment]
> While I get around to setting up a Windows machine, could you please try something? In `autoload/cmake/job.vim`, replace
> 
> https://github.com/cdelledonne/vim-cmake/blob/d82f2a185b17f8390877a8bc4d112dadabe3cea6/autoload/cmake/job.vim#L40
> 
> 
> with
> ```viml
>         let l:term = termopen([a:command], l:options)
> ```
> 
> Basically pass a list to `termopen()` instead of a string. From `:h jobstart()`
> 
> ```
> jobstart({cmd}[, {opts}])				*jobstart()*
> 		Spawns {cmd} as a job.
> 		If {cmd} is a List it runs directly (no 'shell').
> 		If {cmd} is a String it runs in the 'shell', like this:
> 		  :call jobstart(split(&shell) + split(&shellcmdflag) + ['{cmd}'])
> 		(See |shell-unquoting| for details.)
> ```
> 
> I'm curious to see what happens if we run the Bash command "directly".

![image](https://user-images.githubusercontent.com/54179931/151981566-8fc4f8c8-de76-4a25-b596-3300643e3e09.png)
An error is shown after the modification of line 40 and running :CMakeGenerate.

**Comment by cdelledonne** [comment]
@zirco740 I did some major reformatting of the plugin's code, and got rid of the Bash script altogether. I haven't tested extensively, but it seems that the plugin now works under Windows (I tried in a Windows Terminal) as well.

Could you please pull the branch [`major-refactoring`](https://github.com/cdelledonne/vim-cmake/tree/major-refactoring) and test it as well? Would be great to receive some feedback.

Thanks for the patience :)

**Comment by zirco740** [comment]
> 

It works perfectly fine!

**Comment by cdelledonne** [comment]
Great, than I'll merge that PR. The current version seems to only work on Windows using Neovim, which I made explicit in the docs and the README. Will open a follow-up issue to address support for Vim on Windows.
