### ISSUE TITLE
How to switch BuildType Debug/Release quickly?

### ISSUE THREAD

**Issue by ravenxrz** [cdelledonne/vim-cmake#41]
Currently, I  can switch CMake build type by setting g:cmake_default_config='Debug'/'Release'. Is there any better way to do this?
another question is how to use `:CMakeSwitch <config>`, I don't understand what does `<config>` mean.
Thanks!

**Comment by cdelledonne** [comment]
Hi, I think `:CMakeSwitch` is indeed what you're looking for. For instance, to switch to the build configuration `Release`, just run `:CMakeSwitch Release`. You can also trigger autocompletion for the available configurations by pressing `<Tab>` after typing `:CMakeSwitch` in the command line.

By the way, all these commands are documented, try `:help cmake-commands`.

Let me know if this does not solve your problem.

**Comment by ravenxrz** [comment]
> Hi, I think `:CMakeSwitch` is indeed what you're looking for. For instance, to switch to the build configuration `Release`, just run `:CMakeSwitch Release`. You can also trigger autocompletion for the available configurations by pressing `<Tab>` after typing `:CMakeSwitch` in the command line.
> 
> By the way, all these commands are documented, try `:help cmake-commands`.
> 
> Let me know if this does not solve your problem.

Thank you for your reply. I read the manual and know to use these commands now. 
But I get a new issue when use CMakeGenerate:
![image](https://user-images.githubusercontent.com/44746032/158722912-ba5ad623-56a5-45d9-a592-0c98b050ea6c.png)

the `pwd` is: /home/rave/tmp/test_project,  but the project root path is `pwd` followed by a while space, which does not exits.

**Comment by cdelledonne** [comment]
Hmm that's strange. Could you please open a separate issue for that? Please also
- pull the latest `master` branch
- enable logging by setting `g:cmake_log_file` to something like `/tmp/vim-cmake.log` before running any command
- fill in the complete issue template for bugs

Thanks a lot!

**Comment by ravenxrz** [comment]
Sorry for this late reply, I opened a new issue for this.
