### ISSUE TITLE
E117: Unknown function: nvim_open_term

### ISSUE THREAD

**Issue by lazyshawn** [cdelledonne/vim-cmake#43]
### Bug description
Error when running :CMakeGenerate
```
Error detected while processing function cmake#Generate[2]..72[20]..69[17]..66[19]..<SNR>156_CreateConsoleBuffer[2]..<SNR>156_TermSetup:

E117: Unknown function: nvim_open_term
E15: Invalid expression: nvim_open_term(bufnr(''), l:options)
```

### To Reproduce
1. install vim-cmake
2. open an cpp file, running `:CMakeGenerate"

### Behavior with minimal `.vimrc`
```
call plug#begin('~/.config/nvim/plugged')
Plug 'cdelledonne/vim-cmake'
call plug#end()

let g:cmake_link_compile_commands=1
nmap <leader>cg :CMakeGenerate<cr>
nmap <leader>cb :CMakeBuild<cr>
```

### Other info
- OS:  Ubuntu 20.04
- Vim/Neovim version:  0.4.3
- Vim-CMake version (5th line in `:help cmake`):  0.7.0

**Comment by cdelledonne** [comment]
Hey, thanks for reporting this.

It seems indeed that Neovim 0.4.3 does not have the built-in function `nvim_open_term`. The features appears for the first time in Neovim 0.5.0.

I'm not sure I want to add compatibility for older versions of Neovim, it would typically lead to much more messy code and would be harder to maintain—in fact, supporting Neovim and Vim at the same time, and supporting MS-Windows too, is messy already. Plus, Neovim 0.5.0 has been released 9 months ago already, it's just a shame that some distros have very outdated Neovim packages.

This being said, I will look into how much extra code this plugin would need to support older versions of Neovim, and decide what to do then. In the meantime, you could download and use one of the latest Neovim versions (latest is [0.6.1](https://github.com/neovim/neovim/releases/tag/v0.6.1)), you'll also find a plethora of other very cool features in these newer releases, best of all the native LSP client.

**Comment by lazyshawn** [comment]
Thanks. I upgrate nvim to 0.7.0, and it works well now.
