### ISSUE TITLE
CMakeRun command support

### ISSUE THREAD

**Issue by ravenxrz** [cdelledonne/vim-cmake#49]
### Request description

Run an executable file inside vim/nvim using CMakeRun.

### Desired behavior

After executing the CMakeBuild command, we will get a bunch of executable files. It would be very sweet if we could run those files inside vim/nvim,  i.e. run   `:CMakeRun +  exec file + args` in vim/nvim.

### Alternatives solutions

Run the file in a terminal window.

**Comment by cdelledonne** [comment]
Hi thanks for opening this.

This plugin's main goal is to provide an interface to CMake commands, as opposed to a generic interface to Vim/Neovim terminals. Running an arbitrary executable is outside the scope of Vim-CMake's responsibilities.

By the way, what executable files would you like to run? Are they those you generate with CMake's [`add_executable`](https://cmake.org/cmake/help/latest/command/add_executable.html) directive? Are they something else too?

**Comment by ravenxrz** [comment]
> Hi, thanks for opening this.
> 
> This plugin's main goal is to provide an interface to CMake commands, as opposed to a generic interface to Vim/Neovim terminals. Running an arbitrary executable is outside the scope of Vim-CMake's responsibilities.
> 
> By the way, what executable files would you like to run? Are they those you generate with CMake's [`add_executable`](https://cmake.org/cmake/help/latest/command/add_executable.html) directive? Are they something else too?

Yeah.  That's exactly what I want to say. Use CMakeRun to run executable files generated with  `add_executable`  directive. I get this idea from vscode cmake plugin, which shows us a prompt window, and let us pick a target to build and run.

**Comment by cdelledonne** [comment]
I actually wanted to think about this feature request, not dismiss it. I'm just out of free time in this period, will get back to this in the near future :)

I'll re-open

**Comment by cdelledonne** [comment]
Just added support for `:CMakeRun`
