### ISSUE TITLE
Enable jump when :CMakeOpen

### ISSUE THREAD

**Issue by neckutrek** [cdelledonne/vim-cmake#52]
I'd like to be able to focus the cmake console window when running `:CMakeOpen`.
The reason is that I want to toggle line numbers in that window when it has been newly opened.

Even if I set `:let g:cmake_jump=1`, when calling `:CMakeOpen` the window focus is not on the cmake console window.

Perhaps adding a `:CMakeFocus` function could be a nice extension?
Or adding a conditional check on `autoload/cmake/terminal.vim:370` like `if g:cmake_jump==0 && ...` since jumping works for generate/build etc.

**Comment by cdelledonne** [comment]
Hi, thanks for posting this.

Your request makes sense. I've been busy and couldn't work on this plugin lately, but I'll hopefully find some time in these two weeks. Let me get back to you then. Thanks for your patience :)

**Comment by cdelledonne** [comment]
@neckutrek could you please checkout the branch `52-enable-jump-when-cmakeopen` and see if that matches your expected behaviour? The command `:CMakeOpen` now respects the value of `g:cmake_jump`.

**Comment by cdelledonne** [comment]
I've actually merged into `master`, just pulled that and let me know if you see any problems
