### ISSUE TITLE
Close CMake Window on successfull CMakeBuild

### ISSUE THREAD

**Issue by AlexAUT** [cdelledonne/vim-cmake#6]
**Describe the solution you'd like**
It would be awesome to have an option which closes the CMake window after a successful build. Just to avoid the two keystrokes for ```cq```.

Thanks for the great plugin :+1:

**Comment by cdelledonne** [comment]
Hi, thanks for posting this!

I've been thinking about this, and yes, closing the CMake window after a successful `:CMakeGenerate` or `:CMakeBuild` would be a nice option to have.

More in general, I was thinking whether it's worth adding some autocommand events, something like `CMakeBuildOk`, `CMakeBuildError`, etc. That way, the user would be able to do anything on such events.

What do you think? Would events be an overkill? Maybe just a close-on-success options as you suggest is enough to cover all possible needs?

**Comment by AlexAUT** [comment]
Autocommand events would be awesome because one could start the application after a successful build.
For now I have to build with a hotkey and then debug (vimspector) the application with a separate key.

I think having both options would be awesome, however I do not know vimscript and cannot tell how much time it takes to implement it.

**Comment by cdelledonne** [comment]
Two use cases are already enough to go for autocommand events, as far as I'm concerned. I'll pick this up when I'm back from holidays, unless, of course, you'd like to give Vimscript a shot :).
