### ISSUE TITLE
Change directory

### ISSUE THREAD

**Issue by IZenithy** [cdelledonne/vim-cmake#65]
### Request description
When I change my directory, vim-cmake can locate where is the new CMakeLists file is

For example, when I build this project:
![2022-08-28_21:41:19](https://user-images.githubusercontent.com/82327047/187089694-30fc36ed-8de5-4dcd-bfba-75804f48f087.jpg)

And then try to build another project:
![2022-08-28_21:45:44](https://user-images.githubusercontent.com/82327047/187089851-1a00925f-1c72-4778-9fc4-ff7acb0d5fe4.jpg)
It tries to build the old project

### Alternatives solutions
Command that we can use to clear build history

**Comment by cdelledonne** [comment]
Hi, thanks for opening this, and sorry for replying with such a delay.

Vim-CMake was designed in such a way that it only detects project locations when it's first invoked, and as you noticed if you switch to a different project without closing and re-opening the editor it will build the first project it bound to. I don't think it would be very difficult to implement a mechanism to refresh Vim-CMake when changing the current directory, I'll look into this asap and get back to you.

**Comment by cdelledonne** [comment]
I just updated the behavior of Vim-CMake to reinitialize itself upon a change of the current directory (this behavior can be disabled by setting `g:cmake_reinit_on_dir_changed` to `0`). Let me know if that is what you were expecting.

**Comment by IZenithy** [comment]
Perfect 👌
