### ISSUE TITLE
Bug in function RefreshTests

### ISSUE THREAD

**Issue by guskov-roman** [cdelledonne/vim-cmake#66]
### Bug description
By CMakeGenerate  crash with error by function RefreshTests, but there is no test declarate in the project. It is just "Hello World"

### To Reproduce
Just run CMakeGenerate. Clear Debian 11 "bullseye"
1. main.cpp
```
#include <iostream>

using namespace std;

int main () {
    cout << "Hello World!" << endl;
    return 0;
}
```
3. CMakeLists.txt
```
cmake_minimum_required(VERSION 3.5)

project(foo LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

list(APPEND SOURCES main.cpp)

add_executable(foo ${SOURCES})
```
### Behavior with minimal `.vimrc`
syntax on
set number	
set scrolloff=3
set wrap
set showmatch
set autoread
set confirm 
set noswapfile
set incsearch 
set hlsearch	
set ignorecase	
set smartcase
filetype plugin on

" ############################################################################## 
" 				 Plug autoload
" ############################################################################## 

" automatically downloads vim-plug to your machine if not found.
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Define plugins to install
call plug#begin('~/.vim/plugged')
     Plug 'cdelledonne/vim-cmake'
call plug#end()    

let g:cmake_link_compile_commands = 1

### Screenshots

![Screenshot from 2022-09-15 16-09-48](https://user-images.githubusercontent.com/15210963/190429634-dcd79af2-cb7b-4d16-bd4e-d8e9c270e88d.png)

### Other info
- OS: Debian 11 "bullseye"
- Vim/Neovim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 01 2021 01:51:08)
Included patches: 1-2434
Extra patches: 8.2.3402, 8.2.3403, 8.2.3409, 8.2.3428
- Vim-CMake version (5th line in `:help cmake`): 0.10.1
- CMake version (`cmake --version`): 3.18.4

**Comment by cdelledonne** [comment]
Hi, thanks for reporting this, and sorry for replying with such a delay.

There is indeed an issue when using Vim-CMake on Vim. I'll look into it asap and get back to you.

**Comment by cdelledonne** [comment]
I added a fix, please update the plugin and let me know if the problem was solved
