### ISSUE TITLE
Can't run CMakeGenerate after fresh install

### ISSUE THREAD

**Issue by aignacio** [cdelledonne/vim-cmake#72]
### Bug description
After installing the plugin through Vundle, I tried to run :CmakeGenerate and I get the following error:
![image](https://user-images.githubusercontent.com/5991372/198096604-1e52d35d-4682-42b3-9bb1-95700dc5e500.png)

### To Reproduce
1. Install
2.Open vim
3.Run :CMakeGenerate

### Expected behavior
Expect to get the initial cmake files

### Screenshots
![image](https://user-images.githubusercontent.com/5991372/198096739-1f07c247-72ed-4f8e-9570-f5526fa1230f.png)

### Other info
- OS: Ubuntu 22.04.1 LTS
- Vim/Neovim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 13 2022 09:35:02)
Included patches: 1-3995, 4563, 4646, 4774, 4895, 4899, 4901, 4919
- Vim-CMake version (5th line in `:help cmake`): 0.11.0
- CMake version (`cmake --version`): 3.22.1

**Comment by cdelledonne** [comment]
Hi, thanks for reporting this. I did in fact introduce a bug in one of the latest commits. It should be solved now, can you try the latest `master` please?
