### ISSUE TITLE
[Request] Jump to errors

### ISSUE THREAD

**Issue by GGCristo** [cdelledonne/vim-cmake#8]
Your plugin its pretty well designed, I like the idea of using an unique window so I don't have to use the :colder command with ALE, also I can switch easily between buildings, but there is one problem, when an error occurs I cant jump to the line with that error.

I guess implementing this with the terminal window it would be like walking trough hell, so maybe it would be nice to have the option to decide if you want to use the terminal window or a quickfix, but I guess you will still have to write a lot of code to accomplish this.

Anyway I open the issue and maybe someone will come up with some idea.

**Comment by cdelledonne** [comment]
Hey, thank you for the request!

Indeed the implementation is not trivial in both ways, I wish there were a cleaner solution. One day I'll think about it further. Thanks again for opening this.

**Comment by GGCristo** [comment]
Maybe a workaround could be an autocommand in Buffenter for .cpp filetypes, that change the makeprg accordingly to the default build (because when you open a session the build activated its the default one), and when you do :CMakeSwitch or :CMakeGenerate with one argument change again.
The best of both worlds your plugin and  vhdirk/vim-cmake.
Maybe this affect performance because of the autocomand, but that would be fixe it with a boolean variable in the configuration.

**Comment by GGCristo** [comment]
Ok, currently this is my workaround.
In plugin/cmake.vim . line 50
```
autocmd FileType cpp let &makeprg = 'cmake --build ' . g:cmake_default_config
```
In autoload/cmake/switch.vim. line 44
```
let &makeprg = 'cmake --build ' . a:config
```
If CMakebuild find an error I run a regular make.

I know its shabby, but I use it as the last option.
