### ISSUE TITLE
:CMakeToggle

### ISSUE THREAD

**Issue by sillydan1** [cdelledonne/vim-cmake#82]
Since we already have `:CMakeOpen` and `:CMakeClose` it feels like it would be appropriate with a `:CMakeToggle` command that toggles the cmake window.

This _could_ be manually scripted in users' init script file(s), but it would be much cleaner and easier to keybind if it was a built-in feature of the plugin.

**Comment by cdelledonne** [comment]
Hi, thanks for opening this.

I think your request makes sense, and should be fairly easy to implement. Would you be interested in submitting a PR?

**Comment by sillydan1** [comment]
Thanks for merging! I'll be honest, I had completely forgot about the PR 😄

**Comment by cdelledonne** [comment]
I understand :) I didn't want to be pushy so I just finalized it myself. Thanks for the contribution!
