### ISSUE TITLE
If CMakeRun is called, information of CMakeGenerate and CMakeBuild will never show up in the quickfix list

### ISSUE THREAD

**Issue by gzqx** [cdelledonne/vim-cmake#88]
### Bug description
If CMakeRun is called, information of CMakeGenerate and CMakeBuild will never show up in the quickfix list

### To Reproduce
1. Run CMakeRun
2. Add a bug to the code. Run CMakeBuild.

### Expected behavior
The quickfix list of CMakeBuild overwrite the one occupied by CMakeRun.

**Comment by cdelledonne** [comment]
Hi, thanks for the report.

While trying to reproduce your issue, I actually ran into another problem: the sequence `:CMakeRun` and `:CMakeBuild`  would fail altogether. This should now be fixed on the latest `master`.

I cannot reproduce your problem though. The sequence

1. Run `:CMakeRun <target>`
2. Add a bug to the code
3. Run `:CMakeBuild`

produces the expected results, i.e. the Vim-CMake window shows the errors as reported by CMake, and the quickfix list also displays the errors accordingly.

Also when you say

> The quickfix list of CMakeBuild overwrite the one occupied by CMakeRun.

I'm not sure what you mean exactly, as `:CMakeRun` does not produce any quickfix list.

**Comment by gzqx** [comment]
This indeed seems to fix my issue. I guess somewhere I misunderstood the behavior of the plugin. Thank you!
