### ISSUE TITLE
[ERROR] Job still runing in buffer

### ISSUE THREAD

**Issue by GGCristo** [cdelledonne/vim-cmake#9]
**Describe the bug** **To Reproduce**
Using commands like :CMakeCenerate or :CMakeCuild let the procces running in the background so when I try to exist vim an E947 doesn't let me leave.

**Expected behavior**
The script should finish or kill the process when I leave vim

**Screenshots**
![Screenshot_20200818_232106](https://user-images.githubusercontent.com/58046649/90571438-a5774080-e1a9-11ea-827b-7bbd1262b6be.png)

**Other info**
- OS: Linux/Ubuntu
- Vim/Neovim version: VIm 8.2
- Vim-CMake version (5th line in `:help cmake`): 0.2.2

Edit: Its enough to open the window (:CMakeOpen)

**Comment by cdelledonne** [comment]
Hi, thank you for reporting this.

I'll try to reproduce it in the next few days as soon as I find some time. To recap, you launch Vim, then call `:CMakeOpen`, then try to quit Vim, and you get the error. Correct?

**Comment by GGCristo** [comment]
Yes.

**Comment by cdelledonne** [comment]
The latest commit should solve this issue. Could you try to update your plugin and check if the error disappeared?

**Comment by GGCristo** [comment]
Yes, it looks like it works fine know.
