### ISSUE TITLE
error CMakeGenerate OS Windows 10/11

### ISSUE THREAD

**Issue by ferrerama** [cdelledonne/vim-cmake#91]
### Bug description
It was used on Linux and it works great, but on Windows it generates an error.

### To Reproduce
1. On OS Windows use MinGW. For example, I use in windows terminal CMake .. -G "MinGW Makefiles y well.
2. If Run in Neovim the command CMakeGenerate, its  give error, no detect projects and Compiler.

### Expected behavior
I use command CMakeGenerate in Linux and run good.

### Behavior with minimal `.vimrc`
...

### Screenshots
Run: CMakeClean, because before I use the cmake on windows terminal. it is the result clean.
![image](https://github.com/cdelledonne/vim-cmake/assets/77178939/b83bec12-9a9d-489a-ae0b-97a2afb55e91)

following: Run CMakeGenerate and this error show.
![image](https://github.com/cdelledonne/vim-cmake/assets/77178939/3fd7d4d7-97f4-4b11-85a8-e99dee0195ef)

### Other info
- OS: Windows 11
- Vim/Neovim version: Neovim v0.9.4
- Vim-CMake version: latest
- CMake version : 3.27.2

### Additional context
The problem it is command CMakeGenerate, other commands use good,

Content CMakeLists.txt
![image](https://github.com/cdelledonne/vim-cmake/assets/77178939/fe8133ee-4f3c-4dc6-8eb2-57017966fbd9)

**Comment by cdelledonne** [comment]
Hi, thanks for asking this.

You have to run the `:CMakeGenerate` command with the same options as you would run `cmake` from the command line. So if you would pass ` -G "MinGW Makefiles"` to `cmake`, you'd have to call the command as
```
:CMakeGenerate  -G "MinGW Makefiles"
```

Did you try this already?

**Comment by cdelledonne** [comment]
By the way, instead of passing this option to `:CMakeGenerate` all the time, you can also use the configuration option `g:cmake_generate_options`.

**Comment by ferrerama** [comment]
> Hi, thanks for asking this.
> 
> You have to run the `:CMakeGenerate` command with the same options as you would use to run `cmake` from the command line. So if you would pass `-G "MinGW Makefiles"` to `cmake`, you'd have to call the command as
> 
> ```
> :CMakeGenerate -G "MinGW Makefiles"
> ```
> 
> Did you try this already?

It works perfect, thank you. I never thought it was like running such as terminal (the commands).

Please, one dude, is it possible to change the color to transparent of the background on window where the CMake execution is displayed ?

**Comment by ferrerama** [comment]
> By the way, instead of passing this option to `:CMakeGenerate` all the time, you can also use the configuration option `g:cmake_generate_options`.

yes, I use: 'g:cmake_generate_options' thanks.

**Comment by cdelledonne** [comment]
> Please, one dude, is it possible to change the color to transparent of the background (terminal), where the CMake execution is displayed ?
It currently takes the color of the installed scheme.

Are you asking why the Vim-CMake window does not have the same background color as the other Vim windows? Or something else? I wouldn't know, you'd have to try what happens with a minimal vimrc, and see if the problem lies in your configuration/colorscheme or not.
