### ISSUE TITLE
No work 

### ISSUE THREAD

**Issue by ferrerama** [cdelledonne/vim-cmake#95]
Hello again,
I tried install and not download, the resulta is failed.

It is temporaly?.

**Comment by cdelledonne** [comment]
Hi, you have to give me more details. What failed? What are you seeing?

**Comment by ferrerama** [comment]
> Hi, you have to give me more details. What failed? What are you seeing?

thanks.

when installing in neovim it fails.
it happened in OS Linux or Windows.

![image](https://github.com/cdelledonne/vim-cmake/assets/77178939/9a0973f0-5672-4fb9-84f7-32b465a31d35)

When open nvim, this error.

![image](https://github.com/cdelledonne/vim-cmake/assets/77178939/443814e1-81be-4730-9875-8857996479a5)

this show

![image](https://github.com/cdelledonne/vim-cmake/assets/77178939/578ea7d5-1fb9-4986-be0b-7a4dc3f3ba83)

**Comment by Issafalcon** [comment]
Hi @cdelledonne - Loving the plugin! Only just started to use it as I start my journey learning C++.

I'm also seeing something like the above. Using Lazy.nvim as my package manager I get the following due to the reliance on ssh:

```
    ○ vim-cmake  BufReadPost 
        Cloning into '/home/adam/.local/share/nvim/lazy/vim-cmake'...
        remote: Enumerating objects: 565, done.        
        remote: Counting objects: 100% (233/233), done.        
        remote: Compressing objects: 100% (125/125), done.        
        remote: Total 565 (delta 103), reused 182 (delta 94), pack-reused 332        
        Receiving objects: 100% (565/565), 78.98 KiB | 1.46 MiB/s, done.
        Resolving deltas: 100% (190/190), done.
        Submodule 'autoload/libs' (git@github.com:cdelledonne/vim-libs.git) registered for path 'autoload/libs'
        Cloning into '/home/adam/.local/share/nvim/lazy/vim-cmake/autoload/libs'...
        Host key verification failed.
        fatal: Could not read from remote repository.

        Please make sure you have the correct access rights
        and the repository exists.
        fatal: clone of 'git@github.com:cdelledonne/vim-libs.git' into submodule path '/home/adam/.local/share/nvim/lazy/vim-cmake/autoload/libs' failed
        Failed to clone 'autoload/libs'. Retry scheduled
        Cloning into '/home/adam/.local/share/nvim/lazy/vim-cmake/autoload/libs'...
        Host key verification failed.
        fatal: Could not read from remote repository.

        Please make sure you have the correct access rights
        and the repository exists.
        fatal: clone of 'git@github.com:cdelledonne/vim-libs.git' into submodule path '/home/adam/.local/share/nvim/lazy/vim-cmake/autoload/libs' failed
        Failed to clone 'autoload/libs' a second time, aborting
```

I imagine #96 should fix this right?

**Comment by cdelledonne** [comment]
I had indeed overlooked this. Thanks @ferrerama and @Issafalcon for reporting, and thanks @oj-lappi for the PR. I'll merge the fix right away.

**Comment by ferrerama** [comment]
> I had indeed overlooked this. Thanks @ferrerama and @Issafalcon for reporting, and thanks @oj-lappi for the PR. I'll merge the fix right away.

Thank you very much for your attention, it works excellent again. happy new year.
